version: '3'

services:
  wildfly:
    image: wojleg256/wildfly-for-bookshop
    build: 
      context: .
      dockerfile: Dockerfile-wildfly
    ports:
      - "9990:9990"
      - "8080:8080"
      - "8787:8787"
    depends_on:
      - psdb
    volumes:
      - ./artifacts:/opt/jboss/wildfly/standalone/deployments
  psdb:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin111
    
  