version: '3'

services:
  wildfly:
    image: wojleg256/wildfly-for-bookshop
    build: Dockerfile-wildfly
    ports:
      - "9990:9990"
      - "8080:8080"
    volumes:
      - ./artifacts:/opt/jboss/wildfly/standalone/deployments