FROM jboss/wildfly:16.0.0.Final

USER root

#install wget
RUN yum -y install wget

#install jdk 12
RUN	wget https://download.java.net/java/GA/jdk12.0.1/69cfe15208a647278a19ef0990eea691/12/GPL/openjdk-12.0.1_linux-x64_bin.tar.gz && \
	mkdir /usr/java && \
	tar xvzf openjdk-12.0.1_linux-x64_bin.tar.gz -C /usr/java && \
	rm -f openjdk-12.0.1_linux-x64_bin.tar.gz 

#set java envs
ENV JAVA_HOME /usr/java/jdk-12.0.1
ENV PATH /usr/java/jdk-12.0.1/bin:$PATH

USER jboss

WORKDIR /opt/jboss/wildfly/bin

# add user 
RUN sh add-user.sh admin admin123

# add datasource 
ADD create_datasource.sh .
RUN wget --no-cookies --no-check-certificate https://jdbc.postgresql.org/download/postgresql-42.2.5.jar && \
	sh create_datasource.sh && \
	rm -rf ../standalone/configuration/standalone_xml_history/current && \
	rm create_datasource.sh && \
	rm postgresql-42.2.5.jar

# make remote debug option works with java 10  
RUN sed -i -- 's/dt_socket,address=/dt_socket,address=*:/g' standalone*
# added -Dfile.encoding=UTF-8 to fix problem with encoding hibernate import file
RUN sed -i -- 's/JAVA_OPTS="-Xms64m -Xmx512m/JAVA_OPTS="-Xms64m -Xmx512m -Dfile.encoding=UTF-8/g' standalone*

# EXPOSE PORTS 
EXPOSE 9990
EXPOSE 8080
EXPOSE 8787

# RUN container with standalone 
CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0", "--debug"]


