FROM jboss/wildfly:13.0.0.Final

USER root

#install wget
RUN yum -y install wget

#install jdk 10
RUN	wget --no-cookies --no-check-certificate --header "Cookie: oraclelicense=accept-securebackup-cookie" \
    http://download.oracle.com/otn-pub/java/jdk/10.0.2+13/19aef61b38124481863b1413dce1855f/jdk-10.0.2_linux-x64_bin.rpm && \
	yum -y install jdk-10.0.2_linux-x64_bin.rpm && \
	rm jdk-10.0.2_linux-x64_bin.rpm && yum clean all
	
#set java envs
ENV JAVA_HOME /usr/java/jdk-10.0.2
ENV PATH $PATH:/usr/java/jdk-10.0.2/bin

USER jboss

WORKDIR /opt/jboss/wildfly/bin

# add user 
RUN sh add-user.sh admin admin123

# make remote debug option works with java 10  
RUN sed -i -- 's/dt_socket,address=/dt_socket,address=*:/g' standalone*

# EXPOSE PORTS 
EXPOSE 9990
EXPOSE 8080
EXPOSE 8787

# RUN container with standalone 
CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0", "--debug"]


