version: '3'

services:
  wildfly:
    image: wojlegaw256/wildfly-for-bookshop
    build: 
      context: .
      dockerfile: Dockerfile-wildfly
    ports:
      - "9990:9990"
      - "8080:8080"
      - "8787:8787"
    depends_on:
      - bookShopDB
    volumes:
      - ./artifacts:/opt/jboss/wildfly/standalone/deployments
    healthcheck:
     test: ["CMD", "curl", "-f", "http://192.168.99.100:9990"]
     interval: 1s
     timeout: 1s
     retries: 100
  bookShopDB:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=book_shop_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin111
    
  