version: '3'

services:
  wildfly:
    image: wojleg256/wildfly-for-bookshop
    build: 
      context: .
      dockerfile: Dockerfile-wildfly
    ports:
      - "9990:9990"
      - "8080:8080"
      - "8787:8787"
    depends_on:
      - oracledb
    volumes:
      - ./artifacts:/opt/jboss/wildfly/standalone/deployments
  oracledb:
    image: oracle/database:18.3.0-se2
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=oracle
    
  